[settings]
# enable nothing so disable everything
enable_tools = []
# disable_tools = [
#   "act",
#   "python",
#   "actionlint",
#   "cargo:sqlx-cli",
#   "cargo:*",  # Do globals work?
#   "aws",
#   "aws-cli",
#   "awscli",
#   "bat",
#   "bfs",
#   "bottom",
#   "buf",
#   "cargo:release-plz",
#   "cmake",
#   "colima",
#   "direnv",
#   "dvc",
#   "eza",
#   "fd",
#   "fzf",
#   "gcloud",
#   "gh",
#   "git-lfs",
#   "go",
#   "imagemagick",
#   "just",
#   "kubectl",
#   "lazygit",
#   "lima",
#   "lua",
#   "luajit",
#   "make",
#   "marksman",
#   "neovim",
#   "node",
#   "npm",
#   "pandoc",
#   "perl",
#   "pnpm",
#   "protobuf",
#   "rclone",
#   "rg",
#   "ripgrep",
#   "ruby",
#   "shellcheck",
#   "sqlite",
#   "supabase",
#   "terraform",
#   "tree-sitter",
#   "typstyle",
#   "uv",
#   "yazi"
# ]
