#!/bin/bash

# This hook is used in my dotfiles repository to encourage mirroring between
# my local computer state and whats on github
# from githooks(5), the interface is
# <local ref> SP <local object name> SP <remote ref> SP <remote object name> LF

GIT_DIR="$(git rev-parse --git-dir)"

function update_brewfile() {
  mkdir -p "$GIT_DIR/../_MANIFESTS/brew"
  cd "$GIT_DIR/../_MANIFESTS/brew" && brew bundle dump --force
  # Kept for backwards compabability
  cp "$GIT_DIR/../_MANIFESTS/brew/Brewfile" "$GIT_DIR/../brew"
}

function update_uv() {
  mkdir -p "$GIT_DIR/../_MANIFESTS/uv"
  cd "$GIT_DIR/../_MANIFESTS/uv" && uv tool list >uv_tool_list_output.txt
}

function update_cargo() {
  mkdir -p "$GIT_DIR/../_MANIFESTS/cargo"
  cd "$GIT_DIR/../_MANIFESTS/cargo" && cargo install --list >cargo_install_list_output.txt
}

function update_nix() {
  mkdir -p "$GIT_DIR/../_MANIFESTS/nix"
  cd "$GIT_DIR/../_MANIFESTS/nix" && nix profile list --json >profile.json
}

(update_brewfile)

(update_uv)

(update_cargo)

(update_nix)
