--- Otter and fffnvim do not play nicely, why can't we have nice things?
--- Disabling entire it gets fixed
--- I hate to be this guy but its been nothing but problems since I
--- use this plugin. Really frustrating.
return {}
-- return {
--   "dmtrKovalenko/fff.nvim",
--   build = "cargo build --release",
--   enabled = false,
--   enable = false,
--   lazy = false,
--   -- or if you are using nixos
--   -- build = "nix run .#release",
--   opts = {
--     debug = false,
--     -- pass here all the options
--   },
--   keys = {
--     {
--       "ff", -- try it if you didn't it is a banger keybinding for a picker
--       function()
--         require("fff").find_files() -- or find_in_git_root() if you only want git files
--       end,
--       desc = "Open file picker",
--     },
--   },
-- }
